pub mod core {
    pub mod yang {
        pub const NOUN: [&str; 20] = [
            "Sun",
            "Day",
            "Point",
            "Summer",
            "Fire",
            "War",
            "Lyrics",
            "Father",
            "Boy",
            "Cockeral",
            "Heaven",
            "God",
            "Mountain",
            "Head",
            "Front",
            "Lightning",
            "Eyes",
            "Soul",
            "South",
            "Light",
        ];
        pub const VERB: [&str; 26] = [
            "Winning",
            "Appearing",
            "Leading",
            "Seeing",
            "Initiating",
            "Sending",
            "Arousing",
            "Energising",
            "Charging",
            "Animating",
            "Conveying",
            "Directing",
            "Transmitting",
            "Relaying",
            "Consigning",
            "Multiplying",
            "Augmenting",
            "Surging",
            "Lifting",
            "Fighting",
            "Enchanting",
            "Generating",
            "Articulating",
            "Telling",
            "Starting",
            "Attacking",
        ];
        pub const ADVERB: [&str; 25] = [
            "Up",
            "Favorably",
            "Decisively",
            "Bravely",
            "Principally",
            "Initially",
            "Fervently",
            "Vigorously",
            "Firmly",
            "Vivaciously",
            "Immediately",
            "Exactly",
            "Bluntly",
            "Creatively",
            "Combatively",
            "Enjoyably",
            "Agreeably",
            "Willfully",
            "Intensely",
            "Obstinately",
            "Determinedly",
            "Persistently",
            "Inflexibly",
            "Wildly",
            "Loudly",
        ];
        pub const ADJECTIVE: [&str; 26] = [
            "White",
            "Bright",
            "Warm",
            "Dry",
            "Interesting",
            "Male",
            "Strong",
            "Large",
            "Positive",
            "Rich",
            "Long",
            "Thick",
            "Good",
            "Right",
            "Happy",
            "Open",
            "Outside",
            "Full",
            "High",
            "Hard",
            "Firm",
            "New",
            "Arrogant",
            "Conceited",
            "Inconsiderate",
            "Careless",
        ];
    }
    pub mod yin {
        pub const NOUN: [&str; 20] = [
            "Moon", "Night", "Surface", "Winter", "Water", "Peace", "Melody", "Mother", "Girl",
            "Hen", "Earth", "Demon", "Lake", "Tail", "Back", "Thunder", "Ears", "Body", "North",
            "Shade",
        ];
        pub const VERB: [&str; 26] = [
            "Losing",
            "Hiding",
            "Following",
            "Hearing",
            "Responding",
            "Receiveing",
            "Resolving",
            "Consummating",
            "Crowning",
            "Terminating",
            "Cancelling",
            "Concluding",
            "Completing",
            "Gaining",
            "Procuring",
            "Supporting",
            "Caring",
            "Accomodating",
            "Guarding",
            "Listening",
            "Maintaining",
            "Concentrating",
            "Catching",
            "Soothing",
            "Maturing",
            "Defending",
        ];
        pub const ADVERB: [&str; 25] = [
            "Down",
            "unsuccessfully",
            "Invisibly",
            "Sensitively",
            "emotionally",
            "Sympathetically",
            "Cordially",
            "Diligently",
            "Flexibly",
            "Reasonably",
            "Subsequently",
            "Extensively",
            "Upliftingly",
            "Compassionately",
            "Encouragingly",
            "Helpfully",
            "Peacefully",
            "Amiably",
            "Complacently",
            "Gently",
            "Mildly",
            "Calmly",
            "Carefully",
            "Discreetly",
            "Quietly",
        ];
        pub const ADJECTIVE: [&str; 26] = [
            "Black",
            "Dark",
            "Cold",
            "Wet",
            "Boring",
            "Female",
            "Weak",
            "Small",
            "Negative",
            "Poor",
            "Short",
            "Thin",
            "Bad",
            "Left",
            "Sad",
            "Close",
            "Inside",
            "Empty",
            "Low",
            "Soft",
            "Flexible",
            "Old",
            "Kind",
            "Patient",
            "Considerate",
            "Careful",
        ];
    }
}

pub mod bigram {
    pub mod yang_yang {
        pub const NOUN: [&str; 23] = [
            "Heaven",
            "Sun",
            "Air",
            "Creation",
            "Initiation",
            "Assertiveness",
            "Current",
            "South",
            "Summer ",
            "Noon",
            "Buds",
            "Blue",
            "Father",
            "Determination",
            "Nose",
            "Breath",
            "Politicians",
            "Administrators",
            "Living Room",
            "Airplane",
            "Power",
            "Green",
            "Supernatural",
        ];
        pub const VERB: [&str; 20] = [
            "Activating",
            "Ascending",
            "Radiating",
            "Blowing",
            "Creating",
            "Initiating",
            "Dominating",
            "Asserting",
            "Energising",
            "Controlling",
            "Boiling",
            "Expanding",
            "Smelling",
            "Breathing",
            "Running",
            "Strategising",
            "Planning",
            "Flying",
            "Displaying",
            "Leading",
        ];
        pub const ADVERB: [&str; 13] = [
            "Very",
            "Certainly",
            "Completely",
            "Justly",
            "victoriously",
            "powerfully",
            "angrily",
            "always",
            "quickly",
            "defiantly",
            "dramatically",
            "only",
            "technically",
        ];
        pub const ADJECTIVE: [&str; 11] = [
            "Your",
            "Active",
            "Those",
            "Internal",
            "Amazing",
            "Important",
            "Arrogant",
            "Conceited",
            "condescending",
            "unkind",
            "Aloof",
        ];
    }
    pub mod yang_yin {
        pub const NOUN: [&str; 22] = [
            "Life",
            "Time",
            "Water",
            "Endurance",
            "Origin",
            "Stong",
            "Determination",
            "Vibration",
            "East",
            "Spring",
            "Morning",
            "Seeds",
            "Black",
            "Daughter",
            "Rationality",
            "Ears",
            "Blood",
            "Scientists",
            "Engineers",
            "Bathroom",
            "Ship",
            "Money",
        ];
        pub const VERB: [&str; 17] = [
            "Declining",
            "Living",
            "Raining",
            "Enduring",
            "Trying",
            "Vibrating",
            "Slipping",
            "Warming",
            "Opening",
            "Listening",
            "Growing",
            "Analysing",
            "Building",
            "Navigating",
            "Saving",
            "Inspiring",
            "Giving",
        ];
        pub const ADVERB: [&str; 12] = [
            "Quite",
            "Almost",
            "Practically",
            "Bravely",
            "vivaciously",
            "fortunately",
            "anxiously",
            "occasionally",
            "Down",
            "slowly",
            "awkwardly",
            "evenly",
        ];
        pub const ADJECTIVE: [&str; 5] = ["Her", "This", "Great", "Interesting", "Attentive"];
    }
    pub mod yin_yang {
        pub const NOUN: [&str; 0] = [];
        pub const VERB: [&str; 0] = [];
        pub const ADVERB: [&str; 0] = [];
        pub const ADJECTIVE: [&str; 0] = [];
    }
    pub mod yin_yin {
        pub const NOUN: [&str; 0] = [];
        pub const VERB: [&str; 0] = [];
        pub const ADVERB: [&str; 0] = [];
        pub const ADJECTIVE: [&str; 0] = [];
    }
}
