pub mod core {
    pub mod yang {
        pub const NOUN: [&str; 20] = [
            "Sun",
            "Day",
            "Point",
            "Summer",
            "Fire",
            "War",
            "Lyrics",
            "Father",
            "Boy",
            "Cockeral",
            "Heaven",
            "God",
            "Mountain",
            "Head",
            "Front",
            "Lightning",
            "Eyes",
            "Soul",
            "South",
            "Light",
        ];
        pub const VERB: [&str; 26] = [
            "Winning",
            "Appearing",
            "Leading",
            "Seeing",
            "Initiating",
            "Sending",
            "Arousing",
            "Energising",
            "Charging",
            "Animating",
            "Conveying",
            "Directing",
            "Transmitting",
            "Relaying",
            "Consigning",
            "Multiplying",
            "Augmenting",
            "Surging",
            "Lifting",
            "Fighting",
            "Enchanting",
            "Generating",
            "Articulating",
            "Telling",
            "Starting",
            "Attacking",
        ];
        pub const ADVERB: [&str; 25] = [
            "Up",
            "Favorably",
            "Decisively",
            "Bravely",
            "Principally",
            "Initially",
            "Fervently",
            "Vigorously",
            "Firmly",
            "Vivaciously",
            "Immediately",
            "Exactly",
            "Bluntly",
            "Creatively",
            "Combatively",
            "Enjoyably",
            "Agreeably",
            "Willfully",
            "Intensely",
            "Obstinately",
            "Determinedly",
            "Persistently",
            "Inflexibly",
            "Wildly",
            "Loudly",
        ];
        pub const ADJECTIVE: [&str; 26] = [
            "White",
            "Bright",
            "Warm",
            "Dry",
            "Interesting",
            "Male",
            "Strong",
            "Large",
            "Positive",
            "Rich",
            "Long",
            "Thick",
            "Good",
            "Right",
            "Happy",
            "Open",
            "Outside",
            "Full",
            "High",
            "Hard",
            "Firm",
            "New",
            "Arrogant",
            "Conceited",
            "Inconsiderate",
            "Careless",
        ];
    }
    pub mod yin {
        pub const NOUN: [&str; 20] = [
            "Moon", "Night", "Surface", "Winter", "Water", "Peace", "Melody", "Mother", "Girl",
            "Hen", "Earth", "Demon", "Lake", "Tail", "Back", "Thunder", "Ears", "Body", "North",
            "Shade",
        ];
        pub const VERB: [&str; 26] = [
            "Losing",
            "Hiding",
            "Following",
            "Hearing",
            "Responding",
            "Receiveing",
            "Resolving",
            "Consummating",
            "Crowning",
            "Terminating",
            "Cancelling",
            "Concluding",
            "Completing",
            "Gaining",
            "Procuring",
            "Supporting",
            "Caring",
            "Accomodating",
            "Guarding",
            "Listening",
            "Maintaining",
            "Concentrating",
            "Catching",
            "Soothing",
            "Maturing",
            "Defending",
        ];
        pub const ADVERB: [&str; 25] = [
            "Down",
            "unsuccessfully",
            "Invisibly",
            "Sensitively",
            "emotionally",
            "Sympathetically",
            "Cordially",
            "Diligently",
            "Flexibly",
            "Reasonably",
            "Subsequently",
            "Extensively",
            "Upliftingly",
            "Compassionately",
            "Encouragingly",
            "Helpfully",
            "Peacefully",
            "Amiably",
            "Complacently",
            "Gently",
            "Mildly",
            "Calmly",
            "Carefully",
            "Discreetly",
            "Quietly",
        ];
        pub const ADJECTIVE: [&str; 26] = [
            "Black",
            "Dark",
            "Cold",
            "Wet",
            "Boring",
            "Female",
            "Weak",
            "Small",
            "Negative",
            "Poor",
            "Short",
            "Thin",
            "Bad",
            "Left",
            "Sad",
            "Close",
            "Inside",
            "Empty",
            "Low",
            "Soft",
            "Flexible",
            "Old",
            "Kind",
            "Patient",
            "Considerate",
            "Careful",
        ];
    }
}

pub mod bigram {
    pub mod yang_yang {
        pub const NOUN: [&str; 23] = [
            "Heaven",
            "Sun",
            "Air",
            "Creation",
            "Initiation",
            "Assertiveness",
            "Current",
            "South",
            "Summer ",
            "Noon",
            "Buds",
            "Blue",
            "Father",
            "Determination",
            "Nose",
            "Breath",
            "Politicians",
            "Administrators",
            "Living Room",
            "Airplane",
            "Power",
            "Green",
            "Supernatural",
        ];
        pub const VERB: [&str; 20] = [
            "Activating",
            "Ascending",
            "Radiating",
            "Blowing",
            "Creating",
            "Initiating",
            "Dominating",
            "Asserting",
            "Energising",
            "Controlling",
            "Boiling",
            "Expanding",
            "Smelling",
            "Breathing",
            "Running",
            "Strategising",
            "Planning",
            "Flying",
            "Displaying",
            "Leading",
        ];
        pub const ADVERB: [&str; 13] = [
            "Very",
            "Certainly",
            "Completely",
            "Justly",
            "Victoriously",
            "Powerfully",
            "Angrily",
            "Always",
            "Quickly",
            "Defiantly",
            "Dramatically",
            "Only",
            "Technically",
        ];
        pub const ADJECTIVE: [&str; 11] = [
            "Your",
            "Active",
            "Those",
            "Internal",
            "Amazing",
            "Important",
            "Arrogant",
            "Conceited",
            "condescending",
            "unkind",
            "Aloof",
        ];
    }
    pub mod yang_yin {
        pub const NOUN: [&str; 22] = [
            "Life",
            "Time",
            "Water",
            "Endurance",
            "Origin",
            "Stong",
            "Determination",
            "Vibration",
            "East",
            "Spring",
            "Morning",
            "Seeds",
            "Black",
            "Daughter",
            "Rationality",
            "Ears",
            "Blood",
            "Scientists",
            "Engineers",
            "Bathroom",
            "Ship",
            "Money",
        ];
        pub const VERB: [&str; 17] = [
            "Declining",
            "Living",
            "Raining",
            "Enduring",
            "Trying",
            "Vibrating",
            "Slipping",
            "Warming",
            "Opening",
            "Listening",
            "Growing",
            "Analysing",
            "Building",
            "Navigating",
            "Saving",
            "Inspiring",
            "Giving",
        ];
        pub const ADVERB: [&str; 12] = [
            "Quite",
            "Almost",
            "Practically",
            "Bravely",
            "Vivaciously",
            "Fortunately",
            "Anxiously",
            "Occasionally",
            "Down",
            "Slowly",
            "Awkwardly",
            "Evenly",
        ];
        pub const ADJECTIVE: [&str; 5] = ["Her", "This", "Great", "Interesting", "Attentive"];
    }
    pub mod yin_yang {
        pub const NOUN: [&str; 21] = [
            "Death",
            "Space",
            "Fire",
            "Consume",
            "Short",
            "spontaneity",
            "Light",
            "West",
            "Autumn",
            "Evening",
            "Flowers",
            "White",
            "Son",
            "Enthusiasm",
            "Eyes",
            "Nerves",
            "Artists",
            "Athletes",
            "Kitchen",
            "Train",
            "Beauty",
        ];
        pub const VERB: [&str; 17] = [
            "Rising",
            "Passing",
            "Burning",
            "Consuming",
            "Brightening",
            "Rising",
            "Changing",
            "Blooming",
            "Enthusing",
            "Seeing",
            "Mating",
            "Imagining",
            "Competing",
            "Moving",
            "Showing",
            "Praising",
            "Taking",
        ];
        pub const ADVERB: [&str; 11] = [
            "Moderately",
            "Partly",
            "Cheerfully",
            "Inncocently",
            "Eagerly",
            "Boastfully",
            "Sometimes",
            "Up",
            "Quickly",
            "Accidentally",
            "Loosely",
        ];
        pub const ADJECTIVE: [&str; 7] = [
            "His",
            "That",
            "Momentary",
            "Bright",
            "Good",
            "Different",
            "Distracted",
        ];
    }
    pub mod yin_yin {
        pub const NOUN: [&str; 22] = [
            "Earth",
            "Moon",
            "Soil",
            "Reception",
            "Submissive",
            "Obedience",
            "Solid",
            "North",
            "Winter",
            "Night",
            "Branches",
            "Red",
            "Mother",
            "Practicality",
            "Mouth",
            "Workers",
            "Farmers",
            "Bedroom",
            "Car",
            "Health",
            "Yellow",
            "Natural",
        ];
        pub const VERB: [&str; 22] = [
            "Existing",
            "Shining",
            "Providing",
            "Receiving",
            "Absorbing",
            "Submitting",
            "Obeying",
            "Supporting",
            "Grounding",
            "Freezing",
            "Transforming",
            "Encouraging",
            "Communicating",
            "Digesting",
            "Resting",
            "Generating",
            "Growing",
            "Travelling",
            "Being",
            "Loving",
            "Considering",
            "Connecting",
        ];
        pub const ADVERB: [&str; 14] = [
            "Mildly",
            "Sparingly",
            "Gracefully",
            "Honestly",
            "Elegantly",
            "Safely",
            "Faithfully",
            "Wearily",
            "Finally",
            "Promptly",
            "Solemnly",
            "Mysteriously",
            "Exactly",
            "Seriously",
        ];
        pub const ADJECTIVE: [&str; 12] = [
            "Our",
            "Passive",
            "These",
            "Gentle",
            "External",
            "Beautiful",
            "Perfect",
            "Humble",
            "Meek",
            "Considerate",
            "Kind",
            "Connected",
        ];
    }
}

pub mod hexagram {
    pub enum Line {
        Yin,
        Yang,
    }
    pub struct Words<'a> {
        Noun: &'a str,
        Verb: &'a str,
        Adjective: &'a str,
    }
    pub struct HLine<'a> {
        Correctness: Line,
        Binary: u8,
        Quality: Words<'a>,
        Social_Position: Words<'a>,
    }
    pub const TOP: HLine = HLine {
        Correctness: Line::Yin,
        Binary: 0,
        Quality: Words {
            Noun: "Truth",
            Verb: "Realising",
            Adjective: "Superior",
        },
        Social_Position: Words {
            Noun: "Teacher",
            Verb: "Guiding",
            Adjective: "Sage",
        },
    };
    pub const FIFTH: HLine = HLine {
        Correctness: Line::Yang,
        Binary: 1,
        Quality: Words {
            Noun: "Expertise",
            Verb: "Ascending",
            Adjective: "Special",
        },
        Social_Position: Words {
            Noun: "King",
            Verb: "Ruling",
            Adjective: "Regal",
        },
    };
    pub const FOURTH: HLine = HLine {
        Correctness: Line::Yin,
        Binary: 0,
        Quality: Words {
            Noun: "Risk",
            Verb: "Readying",
            Adjective: "Precarious",
        },
        Social_Position: Words {
            Noun: "Minister",
            Verb: "Instructing",
            Adjective: "Judicial",
        },
    };
    pub const THIRD: HLine = HLine {
        Correctness: Line::Yang,
        Binary: 1,
        Quality: Words {
            Noun: "Vocation",
            Verb: "Waiting",
            Adjective: "Insecure",
        },
        Social_Position: Words {
            Noun: "Lord",
            Verb: "Leading",
            Adjective: "Distinguished",
        },
    };
    pub const SECOND: HLine = HLine {
        Correctness: Line::Yin,
        Binary: 0,
        Quality: Words {
            Noun: "Education",
            Verb: "Learning",
            Adjective: "Sheltered",
        },
        Social_Position: Words {
            Noun: "Official",
            Verb: "Helping",
            Adjective: "Administrative",
        },
    };
    pub const INITIAL: HLine = HLine {
        Correctness: Line::Yang,
        Binary: 1,
        Quality: Words {
            Noun: "Transition",
            Verb: "Transforming",
            Adjective: "Transient",
        },
        Social_Position: Words {
            Noun: "Folk",
            Verb: "Following",
            Adjective: "Ordinary",
        },
    };
}
